### ISSUE TITLE
Error in "blt setup" step:  Command `drupal:sql:import ` exited with code 1

### ISSUE THREAD

**Issue by BennyAckermann** [wingsuit-designsystem/wingsuit-kickstarter#14]
I am trying to check out the kickstarter package but the automation fails to import the database.

The error originates from "/vendor/drush/drush/src/Sql/SqlBase.php:106". In specific it's the "/vendor/bin/drush @self sql-cli < ../dump/dump.sql --no-interaction --ansi" part.

I am trying on MacOS 11 with every tool at the newest version (npn, yarn etc.).

At first I thought the folder reference is incorrect (the ../ part) but changing that manually was to to no avail.

**Comment by christianwiedemann** [comment]
Hi! Seems to be a problem with the database connection. 
- Is there are more detailed error message. 
- is the settings.local.php already created from blt. Can you check the database connection there?

You can try to run ./vendor/bin/drush sql:cli to check the connection.

**Comment by BennyAckermann** [comment]
That could be the right track.
I can't find a "settings.local.php" file in "docroot/sites/default/".

Looking at the creation process in the Terminal window, I can't see the step where the file should be created either.

The main error message I get is:
`[Exception]`
`Unable to load Drupal settings. Check your --root, --uri, etc.`

The error is originating from "/vendor/drush/drush/src/Sql/SqlBase.php:106". I used the "-vvv" flag that the " Acquia Blt" documentation mentions.

And yes, running " ./vendor/bin/drush sql:cli" manually gets me the same result.

It does not seem to be a chmod problem. The default folder is set to 777.

**Comment by christianwiedemann** [comment]
You can run `blt blt:init:settings` to generate your settings.local.php

**Comment by BennyAckermann** [comment]
Could not find blt/example.local.blt.yml/. Create and commit this file if you'd like to automatically generate blt/local.blt.yml/ based on this template.

Hash salt already exists.

**Comment by christianwiedemann** [comment]
I updated the readme. Either clone the project again and follow the readme instruction or just copy the local.settings.php and add the database connection. Hope this more clear now.

**Comment by BennyAckermann** [comment]
Thank you for helping me out and being so forthcoming.
I got the Kickstarter running (after some more mysql connection problems). Looking good so far.

Now I have to figure out why my component changes (I added a third color to the existing button) are working within Storybook but are not reflected in Drupal even after restarts.
But that is for another place and another time ^_^

**Comment by christianwiedemann** [comment]
yarn dev:drupal

**Comment by BennyAckermann** [comment]
I have that running together with "yarn dev:storybook" and together with my local server.

All of the changes were applied correctly (it seems). They were copied from the source folder into the dist folder.
It's just that when I edit the component in Drupal I can't find the new attributed in the "ui_patterns_settings".

**Comment by christianwiedemann** [comment]
Where do you expect the setting which setting? Is it a field in the drupal entity?

**Comment by christianwiedemann** [comment]
@eatsmarter-benny Open a new issue if you have issues/quesrtion. Will close this...
