### ISSUE TITLE
Confusion about Tailwind CSS forms plugin used

### ISSUE THREAD

**Issue by miloskroulik** [wingsuit-designsystem/wingsuit-kickstarter#16]
In `forms.wingsuit.yml` file, I see that apparently https://tailwindcss-custom-forms.netlify.app/ have been used for styling the forms. However, [that package is compatible with Tailwind CSS 1.x only](https://github.com/tailwindlabs/tailwindcss-custom-forms) ([and it's also documented in the docs](https://tailwindcss.com/docs/upgrading-to-v2#update-typography-and-forms-plugins)) and has been replaced with https://github.com/tailwindlabs/tailwindcss-forms

Is this an omission or is an update of this part planned?

**Comment by christianwiedemann** [comment]
The description in the forms.wingsuit.yml is old. The forms lib is already updated. (@tailwindcss/forms)

**Comment by miloskroulik** [comment]
Thanks, understood.
